config/routes.rb
Rails.application.routes.draw do
  root 'proposals#new'

  resources :proposals, only: [:new, :create, :show] do
    post :generate_ideas, on: :collection
  end

  resources :events, only: [:create]

  delete '/clear_session', to: 'sessions#destroy', as: 'clear_session'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :proposal
end

app/models/proposal.rb
class Proposal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Split::Helper

  before_action :initialize_analytics

  private

  def initialize_analytics
    return unless ENV['SEGMENT_WRITE_KEY'].present?

    @analytics = Segment::Analytics.new(write_key: ENV['SEGMENT_WRITE_KEY'])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    proposal = Proposal.find(params[:proposal_id])
    @event = Event.new(name: event_params[:name], proposal: proposal)

    if @event.save
      track_in_segment(@event)
      head :ok
    else
      head :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end

  def track_in_segment(event)
    return unless @analytics
    @analytics.track(
      user_id: session.id.to_s,
      event: event.name.titleize, # e.g., "Draft Copied"
      properties: {
        proposal_id: event.proposal_id,
        tone_variation: event.proposal.tone
      }
    )
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def new
    @proposal = Proposal.new
  end

  def generate_ideas
    @ideas = IdeaGenerationService.generate_ideas

    respond_to do |format|
      format.turbo_stream
    end
  end

  def create
    tone = ab_test(:tone_of_voice, 'formal', 'passionate')
    generated_draft = DraftingService.generate_draft(proposal_params[:mission], proposal_params[:goal], tone)

    @proposal = Proposal.new(proposal_params.merge(generated_draft: generated_draft, tone: tone))

    if @proposal.save
      track_draft_generated(@proposal)
      redirect_to @proposal, notice: 'Draft was successfully generated.'
    else
      render :new
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  private

  def proposal_params
    params.require(:proposal).permit(:mission, :goal)
  end

  def track_draft_generated(proposal)
    # Track event in our own database
    Event.create(name: 'draft_generated', proposal: proposal)

    # Track event in Segment
    return unless @analytics

    @analytics.track(
      user_id: session.id.to_s, # Using session ID for anonymous user tracking
      event: 'Draft Generated',
      properties: {
        proposal_id: proposal.id,
        tone_variation: proposal.tone
      }
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    reset_session

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path, notice: "Session reset." }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown_to_html(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    markdown = Redcarpet::Markdown.new(renderer, extensions = {})
    markdown.render(text).html_safe
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GrantWriter AI</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="icon" type="image/svg+xml" href="/favicon.svg">

    <%= csrf_meta_tags %>

    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-[100lvh] bg-gray-100">
    <main class="flex-grow">
      <div class="mx-auto px-4 py-8 max-w-5xl">
        <%= yield %>
      </div>
    </main>

    <% if controller_name == 'proposals' && action_name == 'new' %>
      <footer class="bg-gray-100">

       <div class="mx-auto py-6 px-4 max-w-5xl text-center text-xs text-gray-400 relative">
         <div id="toast-container" class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2"></div>

         <%= button_to "Reset Session & Retry A/B Test", clear_session_path, method: :delete, class: "hover:text-gray-600" %>
       </div>
      </footer>
    <% end %>
  </body>
</html>

app/views/proposals/create.html.erb
<h1>Proposals#create</h1>
<p>Find me in app/views/proposals/create.html.erb</p>

app/views/proposals/generate_ideas.turbo_stream.erb
<% if @ideas[:error] %>
  <%= turbo_stream.update "generate_ideas_error" do %>
    <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50" role="alert">
      <%= @ideas[:error] %>
    </div>
  <% end %>
<% else %>
  <%= turbo_stream.update "proposal_mission", @ideas[:mission] %>
  <%= turbo_stream.update "proposal_goal", @ideas[:goal] %>
<% end %>

app/views/proposals/new.html.erb
<h1 class="text-3xl font-bold mb-4">GrantWriter AI Assistant</h1>

<div class="mb-6">
  <p class="mb-2 text-gray-600">
    Enter your nonprofit's mission and the goal of your grant to generate a first draft of your "Statement of Need".
  </p>

  <span class="text-sm text-gray-500">Or use sample data:</span>

  <%= button_to generate_ideas_proposals_path,
              method: :post,
              form_class: "inline-flex align-middle",
              class: "ml-1 inline-flex items-center justify-center h-8 w-8 rounded-full focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-gray-400 disabled:cursor-not-allowed disabled:opacity-50 group",
              form: { data: { controller: "idea-button", action: "turbo:submit-start->idea-button#start turbo:submit-end->idea-button#end", turbo_stream: true } },
              id: "idea-button",
              data: { "idea-button-target": "button" } do %>

    <span data-idea-button-target="buttonContent" class="text-lg leading-none group-hover:animate-shake">
      🎲
    </span>

    <span data-idea-button-target="spinner" class="hidden">
      <svg class="animate-spin h-5 w-5 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>
    </span>
  <% end %>

  <div id="generate_ideas_error" class="text-sm text-red-500 mt-2"></div>
</div>

<hr class="mb-6 border-gray-200">

<%= form_with(model: @proposal, class: "space-y-4", data: { controller: "form-submission", action: "turbo:submit-start->form-submission#start turbo:submit-end->form-submission#end" }) do |form| %>
  <div>
    <%= form.label :mission, class: "block text-sm font-medium text-gray-700" do %>
      Nonprofit Mission <span class="text-red-500">*</span>
    <% end %>

    <%= form.text_area :mission, id: "proposal_mission", rows: 4, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 disabled:bg-gray-100 placeholder:text-gray-400", placeholder: "e.g., To empower underserved youth through technology education.", data: { "form-submission-target": "missionInput", action: "input->form-submission#validateForm" } %>
  </div>

  <div>
    <%= form.label :goal, class: "block text-sm font-medium text-gray-700" do %>
      Grant Goal <span class="text-red-500">*</span>
    <% end %>

    <%= form.text_area :goal, id: "proposal_goal", rows: 4, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 disabled:bg-gray-100 placeholder:text-gray-400", placeholder: "e.g., To secure funding for a new coding bootcamp for 100 students.", data: { "form-submission-target": "goalInput", action: "input->form-submission#validateForm" } %>
  </div>

  <div>
    <button type="submit" id="generate-draft-button" disabled class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 mt-4 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-indigo-500 cursor-pointer disabled:bg-indigo-300 disabled:cursor-not-allowed" data-form-submission-target="submitButton">
      Generate Draft
    </button>
  </div>
<% end %>

app/views/proposals/show.html.erb
<div class="flex flex-col lg:flex-row lg:justify-between lg:items-baseline gap-6 mb-6 lg:w-[calc(65ch+50px)]">
  <h1 class="text-3xl font-bold">Your Generated Draft</h1>

  <%= link_to new_proposal_path, class: "hidden lg:inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white w-fit hover:bg-gray-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-indigo-500 flex-shrink-0" do %>
    <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm.75-11.25a.75.75 0 00-1.5 0v2.5h-2.5a.75.75 0 000 1.5h2.5v2.5a.75.75 0 001.5 0v-2.5h2.5a.75.75 0 000-1.5h-2.5v-2.5z" clip-rule="evenodd" />
    </svg>
    Generate Another Draft
  <% end %>
</div>

<div data-controller="clipboard" data-clipboard-proposal-id-value="<%= @proposal.id %>">
  <div class="flex flex-col lg:flex-row items-start lg:items-end gap-6">
    <div class="bg-gray-50 p-6 rounded-lg border border-gray-200 w-fit">
      <div class="prose" data-clipboard-target="source">
        <%= markdown_to_html(@proposal.generated_draft) %>
      </div>
    </div>

    <button data-action="clipboard#copy" class="hidden lg:inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-indigo-500 disabled:hover:bg-indigo-600 flex-shrink-0">
      Copy to Clipboard

      <span data-clipboard-target="icon">
        <svg class="ml-2 -mr-1 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path d="M7 2a2 2 0 00-2 2v10a2 2 0 002 2h6a2 2 0 002-2V4a2 2 0 00-2-2H7zm0 2h6v10H7V4z"/>
          <path d="M3 6a2 2 0 012-2h1v2H5v10h6v-1h2v1a2 2 0 01-2 2H5a2 2 0 01-2-2V6z"/>
        </svg>
      </span>
    </button>
  </div>

  <div class="lg:hidden mt-4 flex justify-between items-center max-w-[calc(65ch+50px)]">
    <%= link_to new_proposal_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white w-fit hover:bg-gray-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-indigo-500" do %>
      <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm.75-11.25a.75.75 0 00-1.5 0v2.5h-2.5a.75.75 0 000 1.5h2.5v2.5a.75.75 0 001.5 0v-2.5h2.5a.75.75 0 000-1.5h-2.5v-2.5z" clip-rule="evenodd" />
      </svg>
      Generate Another Draft
    <% end %>

    <button data-action="clipboard#copy" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-indigo-500 disabled:hover:bg-indigo-600">
      <span class="sm:hidden">Copy</span>

      <span class="hidden sm:inline">Copy to Clipboard</span>

      <span data-clipboard-target="icon">
        <svg class="ml-2 -mr-1 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path d="M7 2a2 2 0 00-2 2v10a2 2 0 002 2h6a2 2 0 002-2V4a2 2 0 00-2-2H7zm0 2h6v10H7V4z"/>
          <path d="M3 6a2 2 0 012-2h1v2H5v10h6v-1h2v1a2 2 0 01-2 2H5a2 2 0 01-2-2V6z"/>
        </svg>
      </span>
    </button>
  </div>
</div>

<div class="mt-12 text-sm text-gray-500">
  <p>A/B Test Variation:
    <% if @proposal.tone == 'formal' %>
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
        <%= @proposal.tone.capitalize %>
      </span>
    <% else %>
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800">
        <%= @proposal.tone.capitalize %>
      </span>
    <% end %>
  </p>
</div>

app/views/shared/_toast.html.erb
<div data-controller="toast" class="animate-fade-in-up bg-green-500 text-white px-6 py-4 rounded-lg shadow-lg whitespace-nowrap">
  <p><%= message %></p>
</div>